name: publist
description: Publist


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  firebase_core: ^1.3.0
  cloud_firestore: ^2.2.2
  firebase_auth: ^1.4.1
  flutter_progress_hud: ^2.0.0
  modal_progress_hud: ^0.1.3
  provider: ^5.0.0
  flutter_slidable: ^0.6.0
  intl: ^0.17.0
  google_sign_in: ^5.0.3
  flutter_login_facebook: ^1.0.1
  flutter_facebook_auth: ^3.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true


  assets:
    - images/


